// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/habit/index.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Day.tsx";
import * as $$1 from "./islands/HabitSummary.tsx";
import * as $$2 from "./islands/SeriesOfDays.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/habit/index.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Day.tsx": $$0,
    "./islands/HabitSummary.tsx": $$1,
    "./islands/SeriesOfDays.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
